### PR TITLE
fix for the 1.8.7 MenuEntry api changes

### PR DESCRIPTION
**Pull request by Wynadorn**
1.8.7 slightly changes the way in which menu entries have to be added.

### CODE REVIEW

**Comment by Wynadorn** [comment]
Unsure what a release version should have as the `runeLiteVersion` in `build.gradle` maybe it should just be `1.8.7` once that version goes live.

**Comment by geheur** [comment]
Most PRs use `1.8.7-SNAPSHOT`, so I imagine that is fine.

I have fixed my master branch, rebased this, and fixed an issue/deleted unused code.

Also, literally lmao when I saw this PR; my laziness on this fix has been rewarded XD. Thanks!

**Comment by geheur** [comment]
oh, I can just do `-2` instead of `client.getMenuEntries().length - 1`, neat.

**Comment by geheur** [comment]
There is also an `onClick` method on the MenuEntry so this could probably be rewritten not to use `onMenuOptionClicked` any more.

**Pull request merged**
